{{- if .Values.inariServer.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "inari-platform.fullname" . }}-server
  labels:
    {{- include "inari-platform.componentLabels" (dict "root" . "component" "inari-server") | nindent 4 }}
spec:
  type: {{ .Values.inariServer.service.type }}
  selector:
    app.kubernetes.io/component: inari-server
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.inariServer.service.port }}
      targetPort: http
{{- end }}
