{{- if .Values.inariOperator.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "inari-platform.fullname" . }}-operator
  labels:
    {{- include "inari-platform.componentLabels" (dict "root" . "component" "inari-operator") | nindent 4 }}
spec:
  replicas: {{ .Values.inariOperator.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/component: inari-operator
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        {{- include "inari-platform.componentLabels" (dict "root" . "component" "inari-operator") | nindent 8 }}
    spec:
      serviceAccountName: {{ include "inari-platform.fullname" . }}-operator
      containers:
        - name: operator
          image: "{{ .Values.inariOperator.image.repository }}:{{ .Values.inariOperator.image.tag }}"
          imagePullPolicy: {{ .Values.inariOperator.image.pullPolicy }}
          env:
            - name: KEYCLOAK_URL
              value: {{ include "inari-platform.keycloakBaseUrl" . | quote }}
            - name: KEYCLOAK_TOKEN_REALM
              value: inari
            - name: KEYCLOAK_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ include "inari-platform.keycloakAdminSecretName" . }}
                  key: {{ include "inari-platform.keycloakAdminClientIdKey" . }}
            - name: KEYCLOAK_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "inari-platform.keycloakAdminSecretName" . }}
                  key: {{ include "inari-platform.keycloakAdminClientSecretKey" . }}
          {{- with .Values.inariOperator.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
{{- end }}
