{{- if .Values.inariOperator.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "inari-platform.fullname" . }}-operator
  labels:
    {{- include "inari-platform.componentLabels" (dict "root" . "component" "inari-operator") | nindent 4 }}
{{- end }}
